from __future__ import annotations
import glob, sys
from pathlib import Path
import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "scripts" / "curate"))
import schema

CUR = ROOT / "data/curated"
OUT = CUR / "structure_all.parquet"
STRAT = ROOT / "data/STRATIFICATION.md"

def main():
    exclude = {OUT.name, "structure_native_index.parquet"}
    parts = [p for p in glob.glob(str(CUR / "structure_*.parquet"))
             if Path(p).name not in exclude and not Path(p).name.startswith("structure_monomer")]
    frames = [pd.read_parquet(p) for p in sorted(parts)]
    df = pd.concat(frames, ignore_index=True)
    n_raw = len(df)
    df["_res"] = df["resolution"].fillna(99.0)
    df = (df.sort_values(["_res", "complex_id"], kind="stable")
            .drop_duplicates(subset=["receptor_pdb_id", "peptide_chain"], keep="first")
            .drop(columns="_res")
            .reset_index(drop=True))
    df["length_bin"] = df["peptide_len"].fillna(0).astype(int).map(schema.length_bin)

    feat_path = CUR / "complex_features.parquet"
    if feat_path.exists():
        feat = pd.read_parquet(feat_path)
        df = df.drop(columns=[c for c in ("sec_struct", "n_interface_res") if c in df],
                     errors="ignore").merge(feat, on="complex_id", how="left")
        print(f"merged features for {feat.complex_id.nunique()} complexes")
    tc_path = CUR / "complex_target_class.parquet"
    if tc_path.exists():
        tc = pd.read_parquet(tc_path)
        df = df.drop(columns=[c for c in ("target_class",) if c in df], errors="ignore") \
               .merge(tc, on="complex_id", how="left")
        print(f"merged target_class for {tc.complex_id.nunique()} complexes")
    rd = ROOT / "runs/qc/manifest_rederived.csv"
    if rd.exists():
        d = pd.read_csv(rd)
        df = df.merge(d, on="complex_id", how="left")
        for c in ("peptide_len", "peptide_seq", "has_ncaa"):
            df[f"{c}_orig"] = df[c]
        got = df.peptide_len_new.notna()
        df.loc[got, "peptide_len"] = df.loc[got, "peptide_len_new"].astype(int)
        df.loc[got, "peptide_seq"] = df.loc[got, "peptide_seq_new"]
        df.loc[got, "has_ncaa"] = df.loc[got, "has_ncaa_new"].astype(bool)
        df["ncaa_codes"] = df["ncaa_codes"].fillna("")
        df["terminal_caps"] = df["cap_codes"].fillna("")
        df["n_intra_peptide_bonds"] = df["n_intra_bonds"].fillna(0).astype(int)
        df = df.drop(columns=["peptide_len_new", "peptide_seq_new", "has_ncaa_new",
                              "n_intra_bonds", "cap_codes"], errors="ignore")
        df["length_bin"] = df["peptide_len"].fillna(0).astype(int).map(schema.length_bin)
        print(f"re-applied the structure-derived peptide chemistry to {int(got.sum())} complexes")

    df.to_parquet(OUT, index=False)

    print(f"sources: {[Path(p).name for p in sorted(parts)]}")
    print(f"rows: {n_raw} raw -> {len(df)} after dedup\n")
    print("=== by source ===");        print(df.source_dataset.value_counts().to_string())
    print("\n=== cyclic vs linear ==="); print(df.cyclization_type.value_counts().to_string())
    print(f"\n  is_cyclic: {int(df.is_cyclic.sum())} / {len(df)}")
    print("\n=== length bins ===")
    order = ["1-5", "6-10", "11-15", "16-25", "26-50", "51+"]
    print(df.length_bin.value_counts().reindex(order).fillna(0).astype(int).to_string())
    print("\n=== cyclic x length (counts) ===")
    ct = pd.crosstab(df.length_bin, df.is_cyclic).reindex(order).fillna(0).astype(int)
    ct.columns = ["linear" if c is False else "cyclic" for c in ct.columns]
    print(ct.to_string())
    print(f"\n=== ncAA complexes: {int(df.has_ncaa.sum())}")
    yrs = df.deposition_date.dropna().astype(str).str[:4]
    print(f"=== deposition years: {yrs.min()}–{yrs.max()} "
          f"(post-2024: {int((yrs >= '2025').sum())})")
    print(f"\nwrote {OUT}")

    md = ["# Structure-complex stratification (auto-generated)\n",
          "Regenerated by `scripts/curate/combine_manifests.py`. Do not edit by hand.\n",
          f"**{len(df)} peptide–protein complexes** (deduped by pdb+chain).\n",
          "## By source", "```", df.source_dataset.value_counts().to_string(), "```",
          "## Cyclic vs linear", "```", df.cyclization_type.value_counts().to_string(),
          f"\nis_cyclic: {int(df.is_cyclic.sum())} / {len(df)}", "```",
          "## Length bins", "```",
          df.length_bin.value_counts().reindex(order).fillna(0).astype(int).to_string(), "```",
          "## Cyclic x length", "```", ct.to_string(), "```",
          f"\n- ncAA complexes: **{int(df.has_ncaa.sum())}**",
          f"- deposition years: {yrs.min()}–{yrs.max()} (>=2025: {int((yrs >= '2025').sum())})"]
    STRAT.write_text("\n".join(md) + "\n")
    print(f"wrote {STRAT}")

if __name__ == "__main__":
    main()
