from __future__ import annotations
import glob, sys
from pathlib import Path
import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "scripts" / "curate"))
import schema

CUR = ROOT / "data/curated"
REPORT = ROOT / "data/QC_REPORT.md"

FAILS, WARNS, LINES = [], [], []

def check(cond, msg, hard=True):
    if cond:
        LINES.append(f"- OK   {msg}")
    else:
        (FAILS if hard else WARNS).append(msg)
        LINES.append(f"- {'FAIL' if hard else 'WARN'}: {msg}")
    return cond

def seq_len_ok(row):
    s = row.get("peptide_seq")
    n = row.get("peptide_len")
    if not isinstance(s, str) or pd.isna(n):
        return False
    return len(s) == int(n)

def validate_structure(path, df, all_ids):
    name = Path(path).name
    LINES.append(f"\n### {name}  (n={len(df)})")
    req = ["complex_id", "source_dataset", "peptide_seq", "peptide_len",
           "is_cyclic", "cyclization_type"]
    for c in req:
        check(df[c].notna().all(), f"{name}: '{c}' has no nulls")
    check(df.complex_id.is_unique, f"{name}: complex_id unique within file")
    check(df.cyclization_type.isin(schema.CYCLIZATION_TYPES).all(),
          f"{name}: cyclization_type in controlled vocab")
    check((df.peptide_len > 0).all(), f"{name}: peptide_len > 0")
    consistent = df.apply(lambda r: bool(r.is_cyclic) == (r.cyclization_type != "linear"), axis=1)
    check(consistent.all(), f"{name}: is_cyclic consistent with cyclization_type")
    seqlen = df.apply(seq_len_ok, axis=1)
    check(seqlen.all(), f"{name}: peptide_seq length == peptide_len ({int((~seqlen).sum())} bad)",
          hard=False)
    dates = pd.to_datetime(df.deposition_date, errors="coerce")
    has_date = df.deposition_date.notna()
    check((dates.notna() | ~has_date).all(),
          f"{name}: all present deposition_date parse as dates", hard=False)
    dup = df.complex_id[df.complex_id.isin(all_ids)]
    check(dup.empty, f"{name}: no complex_id collisions with other manifests "
          f"({len(dup)} dup)" if not dup.empty else f"{name}: no cross-file id collisions")
    all_ids.update(df.complex_id.tolist())

def validate_affinity(path, df):
    name = Path(path).name
    LINES.append(f"\n### {name}  (n={len(df)})")
    check(df.complex_id.notna().all(), f"{name}: complex_id present")
    check(df.complex_id.is_unique, f"{name}: complex_id unique (within-track)")
    check(df.peptide_seq.fillna("").str.len().gt(0).all(), f"{name}: peptide_seq non-empty")
    check((df.measured_value > 0).all(), f"{name}: measured_value > 0")
    check(df.log_affinity.notna().all() & df.log_affinity.apply(lambda x: x == x).all(),
          f"{name}: log_affinity finite")
    check(df.value_type.notna().all(), f"{name}: value_type present")

def validate_interaction(path, df):
    name = Path(path).name
    LINES.append(f"\n### {name}  (n={len(df)})")
    check(df.complex_id.notna().all(), f"{name}: complex_id present")
    check(df.complex_id.is_unique, f"{name}: complex_id unique")
    check(df.receptor_seq.fillna("").str.len().gt(0).all(), f"{name}: receptor_seq non-empty")
    check(df.peptide_seq.fillna("").str.len().gt(0).all(), f"{name}: peptide_seq non-empty")
    check(df.label.isin([0, 1]).all(), f"{name}: label in {{0,1}}")

def main():
    LINES.append("# QC report\n\nGenerated by `scripts/curate/validate.py`.")
    all_ids: set = set()
    for p in sorted(glob.glob(str(CUR / "structure_*.parquet"))):
        if Path(p).name in ("structure_all.parquet", "structure_native_index.parquet"):
            continue
        validate_structure(p, pd.read_parquet(p), all_ids)
    for p in sorted(glob.glob(str(CUR / "affinity_*.parquet"))):
        validate_affinity(p, pd.read_parquet(p))
    for p in sorted(glob.glob(str(CUR / "interaction_*.parquet"))):
        validate_interaction(p, pd.read_parquet(p))

    allp = CUR / "structure_all.parquet"
    lk = ROOT / "data/splits/leakage.parquet"
    if allp.exists() and lk.exists():
        a = pd.read_parquet(allp); s = pd.read_parquet(lk)
        LINES.append("\n### cross-manifest")
        miss = set(a.complex_id) - set(s.complex_id)
        check(not miss, f"leakage splits cover all {len(a)} combined complexes "
              f"({len(miss)} missing)" if miss else "leakage splits cover all combined complexes")
        check(s.receptor_cluster.notna().all() & s.peptide_cluster.notna().all(),
              "all complexes have receptor+peptide cluster ids")
        if "split_homology" in s:
            span = s.groupby("receptor_cluster").split_homology.nunique()
            check(int((span > 1).sum()) == 0,
                  "homology split is leakage-free (no receptor cluster spans train+test)")
            for col in ("split_random", "split_homology", "split_time"):
                check(s[col].isin(["train", "test"]).all(), f"{col} values in {{train,test}}")
        check(a.sec_struct.notna().all() & a.n_interface_res.notna().all(),
              f"all {len(a)} complexes have enriched sec_struct + interface size", hard=False)

    LINES.append(f"\n## Result\n\n**{len(FAILS)} failures, {len(WARNS)} warnings.**")
    REPORT.write_text("\n".join(LINES) + "\n")
    print("\n".join(LINES[-40:]))
    print(f"\n=> {len(FAILS)} FAIL, {len(WARNS)} WARN. Report: {REPORT}")
    sys.exit(1 if FAILS else 0)

if __name__ == "__main__":
    main()
