import sys
from pathlib import Path

import pandas as pd

ROOT = Path("/12TBDrive1/mega_pep_bench")
df = pd.read_parquet(ROOT / "data/curated/structure_all.parquet")
order = ["1-5", "6-10", "11-15", "16-25", "26-50", "51+"]
sys.path.insert(0, str(ROOT / "scripts/curate"))
import schema
df["length_bin"] = df["peptide_len"].fillna(0).astype(int).map(schema.length_bin)
ct = pd.crosstab(df.length_bin, df.is_cyclic).reindex(order).fillna(0).astype(int)
ct.columns = ["linear" if c is False else "cyclic" for c in ct.columns]
yrs = df.deposition_date.dropna().astype(str).str[:4]

md = ["# Structure-complex stratification (auto-generated)\n",
      "Regenerated by `scripts/curate/write_stratification.py` from the released manifest, so it "
      "reflects the re-derived peptide chemistry. Do not edit by hand.\n",
      f"**{len(df)} peptide–protein complexes** (deduped by pdb+chain).\n",
      "## By source", "```", df.source_dataset.value_counts().to_string(), "```",
      "## Cyclic vs linear", "```", df.cyclization_type.value_counts().to_string(),
      f"\nis_cyclic: {int(df.is_cyclic.sum())} / {len(df)}", "```",
      "## Length bins", "```",
      df.length_bin.value_counts().reindex(order).fillna(0).astype(int).to_string(), "```",
      "## Cyclic x length", "```", ct.to_string(), "```",
      f"\n- ncAA complexes: **{int(df.has_ncaa.sum())}**",
      f"- deposition years: {yrs.min()}–{yrs.max()} (>=2025: {int((yrs >= '2025').sum())})"]
(ROOT / "data/STRATIFICATION.md").write_text("\n".join(md) + "\n")
print(f"ncAA complexes: {int(df.has_ncaa.sum())}")
print(ct.to_string())
print(f"wrote {ROOT / 'data/STRATIFICATION.md'}")
